env:
  browser: true
  es2021: true
extends:
  - eslint:recommended
  - plugin:react/recommended
  - plugin:@typescript-eslint/recommended
overrides: []
parser: "@typescript-eslint/parser"
parserOptions:
  ecmaVersion: latest
  sourceType: module
plugins:
  - react
  - "@typescript-eslint"
settings:
  react:
    version: "detect"
rules:
  indent:
    - error
    - 4
    - SwitchCase: 1
  quotes:
    - error
    - single
  semi:
    - error
    - never
ignorePatterns:
  [
    "/node_modules",
    "/public",
    "/*.json",
    "/*.cjs",
    "/.env",
    "/*.html",
    "/*.conf",
    "/*.ts",
    
  ]
